# Generated by Django 2.1.4 on 2018-12-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thief',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thief_name', models.CharField(max_length=50)),
                ('name_1', models.CharField(max_length=50)),
                ('name_2', models.CharField(max_length=50)),
                ('mass_1', models.IntegerField()),
                ('mass_2', models.IntegerField()),
                ('prize_1', models.IntegerField()),
                ('prize_2', models.IntegerField()),
                ('car_load', models.IntegerField()),
            ],
            options={
                'db_table': 'thief',
            },
        ),
    ]
